- name: Change password for root
  ansible.builtin.user:
    name: root
    password: "{{ hostvars[inventory_hostname].root_password | password_hash('sha512') }}"
    update_password: always

- name: Set ssh PasswordAuthentication to yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: Restart ssh

- name: Permit root login via SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin yes'
  notify: Restart ssh

- name: Clean restrictions from root authorized_keys
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    regexp: '^.*exit 142" (.*)$'
    line: '\1'
    backrefs: yes

- name: Find all SSH config fragments
  ansible.builtin.find:
    paths: /etc/ssh/sshd_config.d
    file_type: file
  register: sshd_fragments

- name: Remove all SSH config fragments
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ sshd_fragments.files }}"
  notify: Restart ssh

