services:
  openvpn:
    build: .
    container_name: openvpn-server
    privileged: true
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "30001-30020:30001-30020/tcp"
      - "31001-31020:31001-31020/tcp"
      - "32000:32000/tcp"
    restart: always