cloud:
  vpn:
    name: advpn
    cpu: 2
    mem: 2
    disk: 10
  jury:
    name: jury
    cpu: 4
    mem: 4
    disk: 30
  vuln:
    name: vuln
    cpu: 4
    mem: 4
    disk: 30
game:
  default_score: 2500
  flag_lifetime: 10
  game_hardness: 10
  inflation: true
  mode: classic
  round_time: 60
  start_time: 2025-09-01 20:00:00
  timezone: Europe/Moscow
tasks:
- checker: bimba/checker.py
  checker_timeout: 20
  checker_type: gevent_pfr
  gets: 1
  name: bimba
  places: 1
  puts: 1
- checker: FileStorage/checker.py
  checker_timeout: 20
  checker_type: gevent_pfr
  gets: 1
  name: file_storage
  places: 1
  puts: 1
- checker: magazinchik/checker.py
  checker_timeout: 20
  checker_type: gevent_pfr
  gets: 1
  name: magazinchik
  places: 1
  puts: 1
- checker: rce-as-a-service/checker.py
  checker_timeout: 20
  checker_type: gevent_pfr
  gets: 1
  name: rce-as-a-service
  places: 1
  puts: 1
- checker: shpagodrach/checker.py
  checker_timeout: 20
  checker_type: gevent
  gets: 1
  name: shpagodrach
  places: 1
  puts: 1
teams:
- name: SIGAN
  id: team1
  ip: 10.80.1.2
  root_password: t3KT6Lzp6Bh3AkEIDlow
- name: mbl
  id: team2
  ip: 10.80.2.2
  root_password: QLVouAkiyrtOCus2jcUH
- name: FreePlay
  id: team3
  ip: 10.80.3.2
  root_password: sPDZX4M9gRXff0dhMhNk
