game:
  default_score: 2500
  flag_lifetime: 10
  game_hardness: 15
  inflation: true
  mode: classic
  round_time: 20
  start_time: 2019-11-30 15:30:00
  timezone: Europe/Moscow
tasks:
- checker: neftetochka/checker.py
  checker_timeout: 10
  checker_type: nfr
  gets: 1
  name: neftetochka
  places: 1
  puts: 1
- checker: explorers/checker.py
  checker_timeout: 15
  checker_type: pfr
  gets: 1
  name: explorers
  places: 1
  puts: 1
teams:
- name: SIGAN
  id: team1
  ip: 10.80.1.2
  root_password: hF1Na540gpz5V2ucMpkz
- name: mbl
  id: team2
  ip: 10.80.2.2
  root_password: dPoW9LmtHYKrj3Z9jSZM
vpn-server:
  name: advpn
jury:
  name: jury
