- name: Copy vpn server files
  ansible.builtin.copy:
    src: ./server
    dest: /
    mode: '0755'

- name: Copy vpn configs
  ansible.posix.synchronize:
    src: ./vpns
    dest: /server
    checksum: true
    owner: false
    group: false
    perms: false

- name: Up vpn server
  ansible.builtin.shell: docker compose up -d --build
  args:
    chdir: /server
