services:
  app:
    restart: unless-stopped
    build: .
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bimba
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - uploads:/root/uploads
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=bimba
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads:
