- name: Grab team tokens
  ansible.builtin.shell: "/forcad/control.py print_tokens"
  register: tokens
  become: true

- name: Write tokens to file on host
  ansible.builtin.copy:
    content: "{{ tokens.stdout }}"
    dest: "{{ inventory_dir }}/../tokens.txt"
    mode: "0755"
  delegate_to: localhost
