- name: Install OpenVPN
  ansible.builtin.apt:
    name: openvpn
    state: present

- name: Copy ovpn config
  ansible.builtin.copy:
    src: ./vpns/{{ group_names[0] }}/{{ inventory_hostname_short }}.ovpn
    dest: /etc/openvpn/config.conf
    mode: '0755'

- name: Uncomment autostart in /etc/default/openvpn
  ansible.builtin.lineinfile:
    path: /etc/default/openvpn
    regexp: '^#AUTOSTART="all"'
    line: 'AUTOSTART="all"'

- name: Restart systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart openvpn service
  ansible.builtin.systemd:
    name: openvpn
    state: restarted
