- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Install basic list of packages
  ansible.builtin.apt:
    name:
      [
        'apt-transport-https',
        'ca-certificates',
        'curl',
        'gnupg2',
        'software-properties-common'
      ]
    state: present
    update_cache: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker packages
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
