- name: Common prepare machines
  hosts: all
  become: true
  roles:
    - upgrades-disable
    - docker

- name: Prepare root user on vulnboxes
  hosts: vuln
  become: true
  roles:
    - root

- name: Configure VPN server
  hosts: vpn_server
  become: true
  roles:
    - vpn-server

- name: Configure VPN clients
  hosts: vuln, jury
  become: true
  roles:
    - vpn-client

- name: Copy services on vulnboxes
  hosts: vuln
  become: true
  roles:
    - prepare-services

- name: Deploy Forcad
  hosts: jury
  become: true
  roles:
    - forcad
