- name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
  ansible.builtin.raw: systemctl disable --now {{ item }}
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.timer'

- name: Reload systemctl daemon to apply the new changes
  ansible.builtin.raw: systemctl daemon-reload

- name: Wait for any possibly running unattended upgrade to finish
  ansible.builtin.raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Purge unattended upgrades
  ansible.builtin.raw: apt-get -y purge unattended-upgrades

- name: Update apt cache
  ansible.builtin.raw: apt-get -y update
